openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/hplussport1/customer/1.0.0
info:
  description: This is an API for HPlusSport customers
  version: "2.0.0"
  title: Customers API
  contact:
    email: you@hplussport.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: customer
    description: customer related calls
paths:
  /customer:
    get:
      tags:
        - customer
      summary: searches customer
      operationId: searchCustomer
      description: |
        By passing in the appropriate options, you can search for
        available customers in the system
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: bad input parameter
components:
  schemas:
    Customer:
      type: object
      required:
        - firstName
        - lastName
        - customerNumber
      properties:
        customerNumber:
          type: string
          example: d290f1ee
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Smith
        phone:
          type: string
          example: '555-555-5555'