# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: HPlus Sports
  description: Common components for HPlus Sport REST APIs
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    Customer:
      type: object
      required:
        - firstName
        - lastName
        - customerNumber
      properties:
        customerNumber:
          type: string
          example: d290f1ee
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Smith
        phone:
          type: string
          example: '555-555-5555'